//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbir.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARACGİRCIK
    {
        public int otoid { get; set; }
        public Nullable<int> otoyerid { get; set; }
        public string otomüsteriad { get; set; }
        public string otomüsterisoyad { get; set; }
        public string otomüsteriplaka { get; set; }
        public string aracgiristarihi { get; set; }
        public string araccıkıstarihi { get; set; }
        public string aracgirissaat { get; set; }
        public string araccıkıssaat { get; set; }
    }
}
