//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbir.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MÜSTERI
    {
        public int müsteriid { get; set; }
        public string müsteriad { get; set; }
        public string müsterisoyad { get; set; }
        public string müsteritcno { get; set; }
        public string müsteritel { get; set; }
        public string müsteriplaka { get; set; }
    }
}
