//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbir.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public int personelid { get; set; }
        public string personelad { get; set; }
        public string personelsoyad { get; set; }
        public string personeltcno { get; set; }
        public string personeltel { get; set; }
        public string personelsifre { get; set; }
    }
}
