//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbir.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YÖNETİCİ
    {
        public int yöneticid { get; set; }
        public string yöneticiad { get; set; }
        public string yöneticisifre { get; set; }
    }
}
