//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcbir.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÜCRET
    {
        public int ücretid { get; set; }
        public string müsterid { get; set; }
        public string giristarihi { get; set; }
        public string cikistarihi { get; set; }
        public string saat { get; set; }
        public Nullable<decimal> tutar { get; set; }
    }
}
